theme: minima
title: Fruit of Preterition
author: Charles Renshaw-Whitman
description: Personal Blog
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
